title: "2025 GSEMOR Variant Calling"
description: "Tutorial for the GSEMOR Workshop"
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

collections:
  pages:
    output: true
    permalink: /:basename/

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"


baseurl: "/2025_GSEMOR_Variant_Calling" 
url: "https://taylorpaisie.github.io"

search_enabled: true
nav_sort: case_insensitive

aux_links:
  "View on GitHub":
    - "https://github.com/taylorpaisie/2025_GSEMOR_Variant_Calling"

back_to_top: true
back_to_top_text: "Back to top"

# 👇 THIS IS THE KEY LINE
include:
  - images
