title: "2025 GSEMOR Variant Calling"
description: "Tutorial for the GSEMOR Workshop"
theme: just-the-docs

# URL structure
baseurl: "/2025_GSEMOR_Variant_Calling" # for GitHub Pages under repo
url: "https://taylorpaisie.github.io"

# Enable search (optional)
search_enabled: true

# Navigation structure
nav_sort: case_insensitive

# Repository link in the header
aux_links:
  "View on GitHub":
    - "https://github.com/taylorpaisie/2025_GSEMOR_Variant_Calling"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Just the Docs settings
just_the_docs:
  logo: "" # You can add a logo URL if desired

